### ISSUE TITLE
Loop or previous error loading module 'iswap'

### ISSUE THREAD

**Issue by dycw** [mizlan/iswap.nvim#34] opened 2021-10-24 02:29 UTC
Part of `packer.nvim` set up:

```
   use {
      "mizlan/iswap.nvim",
      config = function()
         require("iswap").setup {
            -- The keys that will be used as a selection, in order
            -- ('asdfghjklqwertyuiopzxcvbnm' by default)
            keys = "qwertyuiop",

            -- Grey out the rest of the text when making a selection
            -- (enabled by default)
            grey = "disable",

            -- Highlight group for the sniping value (asdf etc.)
            -- default 'Search'
            hl_snipe = "ErrorMsg",

            -- Highlight group for the visual selection of terms
            -- default 'Visual'
            hl_selection = "WarningMsg",

            -- Highlight group for the greyed background
            -- default 'Comment'
            hl_grey = "LineNr",

            -- Automatically swap with only two arguments
            -- default nil
            autoswap = true,
         }
      end,
      requires = "nvim-treesitter/nvim-treesitter",
   }
```

leads to, upon the start of `neovim`:

``` 
Error detected while processing /home/derek/.local/share/nvim/site/pack/packer/start/iswap.n
vim/plugin/iswap.vim:
line    1:
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'iswap'
Press ENTER or type command to continue
```

Is this some sort of import cycle? If so, how does some start to debug?

**Comment by mizlan** [comment] 2021-10-24 05:55
Hi Derek,

Thanks for filing this.

Does this error occur when you use the setup() normally? This might relate
to lazy loading, but I'm not really sure. I'm not even sure I'm writing my
setup() function correctly; I'll compare mine with some other plugins.

Best,
Michael

**Comment by dycw** [comment] 2021-10-24 14:37
Hi @mizlan , the error does occur when run manually.

There's been another plugin, [nvim-treesitter-context](https://github.com/romgrk/nvim-treesitter-context) which seems to run similar problems too.

**Comment by mizlan** [comment] 2021-10-24 17:30
Can you give me a minimal setup to reproduce?

**Comment by mizlan** [comment] 2022-07-14 05:32
Closing because I doubt this is a problem with the plugin per se.

**Closed as completed by mizlan** 2022-07-14 05:32 UTC
Labels: bug, cannot reproduce
